### ISSUE TITLE
Api/articles returns 404

### ISSUE THREAD

**Issue by MarkSoluiman** [AnnetteScott/Speed#2]
I get 404 error when I try to visit: localhost:8000/api/Articles

**Comment by AnnetteScott** [comment]
I can take a look later but I assume it wasn't working when you merged the PR? Is so, it shouldn't have been merged.

**Comment by AnnetteScott** [comment]
I've reviewed and resolved the issues:

- The MongoDB database wasn't set up on mongodb.com, so I’ve taken care of that.
- I've revised the schema.ts file to include missing fields and to replace the enum with a boolean
- The regex for the _id field wasn't functioning as described in the comments (also, it’s unclear why the ID was treated as a URL).
- Added the necessary imports and function calls that were missing.
- Removed 'book' references from both names and comments.

Due to the database not being configured, you would have encountered a 404 error when attempting to retrieve all articles, as none would have existed.

For future issues, please ensure they have a clear title, include screenshots of any errors, and provide all relevant information.
